config/routes.rb
Rails.application.routes.draw do
  resources :question_choices
  resources :question_items
  resources :questions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'question_items/new/:id', to: 'question_items#new'
  get 'question_choices/new/:id', to: 'question_choices#new'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
    has_many :question_items
    
    validates :title, presence: {message:'は必須項目です'}
end

app/models/question_choice.rb
class QuestionChoice < ApplicationRecord
  belongs_to :question_item
  
  validates :content, :value, presence: {message:'は必須項目です'}
  validates :value, numericality: {message:'は必須項目です'}
end

app/models/question_item.rb
class QuestionItem < ApplicationRecord
  belongs_to :question
  has_many :question_choices
  
  validates :content, presence: {message:'は必須項目です'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/question_choices_controller.rb
class QuestionChoicesController < ApplicationController
  before_action :set_question_choice, only: [:show, :edit, :update, :destroy]

  # GET /question_choices
  # GET /question_choices.json
  def index
    @question_choices = QuestionChoice.all
  end

  # GET /question_choices/1
  # GET /question_choices/1.json
  def show
  end

  # GET /question_choices/new
  def new
    @question_choice = QuestionChoice.new
    @question_choice.question_item_id = params[:id]
    @question_item = QuestionItem.find params[:id]
  end

  # GET /question_choices/1/edit
  def edit
  end

  # POST /question_choices
  # POST /question_choices.json
  def create
    @question_choice = QuestionChoice.new(question_choice_params)

    respond_to do |format|
      if @question_choice.save
        format.html { redirect_to '/question_choices/new/' + @question_choice.question_item_id.to_s }
        format.json { render :show, status: :created, location: @question_choice }
      else
        format.html { render :new }
        format.json { render json: @question_choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /question_choices/1
  # PATCH/PUT /question_choices/1.json
  def update
    respond_to do |format|
      if @question_choice.update(question_choice_params)
        format.html { redirect_to @question_choice, notice: 'Question choice was successfully updated.' }
        format.json { render :show, status: :ok, location: @question_choice }
      else
        format.html { render :edit }
        format.json { render json: @question_choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /question_choices/1
  # DELETE /question_choices/1.json
  def destroy
    @question_choice.destroy
    respond_to do |format|
      format.html { redirect_to question_choices_url, notice: 'Question choice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question_choice
      @question_choice = QuestionChoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_choice_params
      params.require(:question_choice).permit(:question_item_id, :content, :value, :correct)
    end
end

app/controllers/question_items_controller.rb
class QuestionItemsController < ApplicationController
  before_action :set_question_item, only: [:show, :edit, :update, :destroy]

  # GET /question_items
  # GET /question_items.json
  def index
    @question_items = QuestionItem.all
  end

  # GET /question_items/1
  # GET /question_items/1.json
  def show
  end

  # GET /question_items/new
  def new
    @question_item = QuestionItem.new
    @question_item.question_id = params[:id]
    @question = Question.find(params[:id])
  end

  # GET /question_items/1/edit
  def edit
  end

  # POST /question_items
  # POST /question_items.json
  def create
    @question_item = QuestionItem.new(question_item_params)

    respond_to do |format|
      if @question_item.save
        format.html { redirect_to '/question_choices/new/' + @question_item.id.to_s}
        format.json { render :show, status: :created, location: @question_item }
      else
        format.html { render :new }
        format.json { render json: @question_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /question_items/1
  # PATCH/PUT /question_items/1.json
  def update
    respond_to do |format|
      if @question_item.update(question_item_params)
        format.html { redirect_to @question_item, notice: 'Question item was successfully updated.' }
        format.json { render :show, status: :ok, location: @question_item }
      else
        format.html { render :edit }
        format.json { render json: @question_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /question_items/1
  # DELETE /question_items/1.json
  def destroy
    @question_item.destroy
    respond_to do |format|
      format.html { redirect_to question_items_url, notice: 'Question item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question_item
      @question_item = QuestionItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_item_params
      params.require(:question_item).permit(:question_id, :content)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to '/question_items/new/' + @question.id.to_s }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/question_choices_helper.rb
module QuestionChoicesHelper
end

app/helpers/question_items_helper.rb
module QuestionItemsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz6</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/question_choices/_form.html.erb
<%= form_for(question_choice) do |f| %>
  <% if question_choice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question_choice.errors.count, "error") %> prohibited this question_choice from being saved:</h2>

      <ul>
      <% question_choice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :選択肢 %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :選択肢の番号 %>
    <%= f.number_field :value %>
  </div>

  <div class="field">
    <%= f.label :正解 %>
    <%= f.check_box :correct %>
  </div>
  
  <div class="field">
    <%= f.label :ここは変更しないで下さい %>
    <%= f.text_field :question_item_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/question_choices/edit.html.erb
<h1>Editing Question Choice</h1>

<%= render 'form', question_choice: @question_choice %>

<%= link_to 'Show', @question_choice %> |
<%= link_to 'Back', question_choices_path %>

app/views/question_choices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Question Choices</h1>

<table>
  <thead>
    <tr>
      <th>Question item</th>
      <th>Content</th>
      <th>Value</th>
      <th>Correct</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @question_choices.each do |question_choice| %>
      <tr>
        <td><%= question_choice.question_item %></td>
        <td><%= question_choice.content %></td>
        <td><%= question_choice.value %></td>
        <td><%= question_choice.correct %></td>
        <td><%= link_to 'Show', question_choice %></td>
        <td><%= link_to 'Edit', edit_question_choice_path(question_choice) %></td>
        <td><%= link_to 'Destroy', question_choice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question Choice', new_question_choice_path %>

app/views/question_choices/new.html.erb
<h1>選択肢の作成</h1>

<%= render 'form', question_choice: @question_choice %>

<%= link_to 'Back', questions_url %>

app/views/question_choices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question item:</strong>
  <%= @question_choice.question_item %>
</p>

<p>
  <strong>Content:</strong>
  <%= @question_choice.content %>
</p>

<p>
  <strong>Value:</strong>
  <%= @question_choice.value %>
</p>

<p>
  <strong>Correct:</strong>
  <%= @question_choice.correct %>
</p>

<%= link_to 'Edit', edit_question_choice_path(@question_choice) %> |
<%= link_to 'Back', question_choices_path %>

app/views/question_items/_form.html.erb
<%= form_for(question_item) do |f| %>
  <% if question_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question_item.errors.count, "error") %> prohibited this question_item from being saved:</h2>

      <ul>
      <% question_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :問題文 %>
    <%= f.text_area :content %>
  </div>
  
  <div class="field">
    <%= f.label :ここは変更しないで下さい %>
    <%= f.text_field :question_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/question_items/edit.html.erb
<h1>Editing Question Item</h1>

<%= render 'form', question_item: @question_item %>

<%= link_to 'Show', @question_item %> |
<%= link_to 'Back', question_items_path %>

app/views/question_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Question Items</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @question_items.each do |question_item| %>
      <tr>
        <td><%= question_item.question %></td>
        <td><%= question_item.content %></td>
        <td><%= link_to 'Show', question_item %></td>
        <td><%= link_to 'Edit', edit_question_item_path(question_item) %></td>
        <td><%= link_to 'Destroy', question_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question Item', new_question_item_path %>

app/views/question_items/new.html.erb
<h1>問題の作成</h1>
<p>「<%= @question.title %>」の問題</p>

<%= render 'form', question_item: @question_item %>

<%= link_to '問題グループ一覧に戻る', '/questions' %>

app/views/question_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @question_item.question %>
</p>

<p>
  <strong>Content:</strong>
  <%= @question_item.content %>
</p>

<%= link_to 'Edit', edit_question_item_path(@question_item) %> |
<%= link_to 'Back', question_items_path %>

app/views/questions/_form.html.erb
<%= form_for(question) do |f| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :タイトル %>
    <%= f.text_area :title %>
  </div>

  <div class="field">
    <%= f.label :内容 %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>問題グループ一覧</h1>

<table>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>内容</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.title %></td>
        <td><%= question.content %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規グループの作成', new_question_path %>

app/views/questions/new.html.erb
<h1>問題グループの作成</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @question.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @question.content %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>